feat: import flags

diff --git a/lib/bootstrap b/lib/bootstrap
--- a/lib/bootstrap
+++ b/lib/bootstrap
@@ -2,94 +2,196 @@
 
 ##
 # Prevent the script from being executed directly.
+#
+# There is no reason to execute this script directly as
+# it does not do anything on its' own.
 ##
-if [[ -z "$0" ]] || [[ "$0" == "bash" ]] || [[ "$0" == "-bash" ]]; then
-  printf "This script may only be sourced from other scripts.\n" 1>&2
-  exit 1
+if [[ -z "$0" ]] || [[ "$0" =~ "bash" ]] || [[ "$0" =~ "-bash" ]]; then
+    printf "[\e[1;91mERROR\e[0m] This script should not be executed directly\n" 1>&2
+    return
 fi
 
+################################################################################
+## Configs
+################################################################################
+if [[ -z "${BOOTSTRAP_DIR}" ]]; then
+    printf "[\e[1;91mERROR\e[0m] BOOTSTRAP_DIR is not set\n" 1>&2
+    exit 1
+fi
+
+declare -g CACHE_DIR="${BOOTSTRAP_DIR}/.cache"
+declare -g BASH_STARTER_VERSION="${BASH_STARTER_VERSION:-master}"
+
+################################################################################
+## Debugging
+################################################################################
 export PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
 
 set -o errexit  # Exit when a command returns a non-zero status code
 set -o nounset  # Exit when an unset variable is used
 set -o pipefail # Exit when a command fails in a pipe. eg. command_will_fail | piped_command
 
-##-- Function Stubs -----------------------------------------------------------
+################################################################################
+## Cache
+################################################################################
+##
+# Returns whether the cache is enabled.
+#
+# The cache is enabled by default but can be disabled
+# by setting the `DISABLE_CACHE' environment variable
+# to any value.
+#
+# Returns:
+#
+#   0 :: The cache is enabled
+#   1 :: The cache is disabled
+##
+function Bootstrap::IsCacheEnabled()
+{
+    if [[ -n "${DISABLE_CACHE:-}" ]]; then
+        return 1
+    fi
+}
+
+################################################################################
+## Import Aliases
+################################################################################
 shopt -s expand_aliases
 
-alias import="Import::Main"
-alias source="Import::Main"
-alias .="Import::Main"
+alias import="bs::import_main"
+alias source="bs::import_main"
+alias .="bs::import_main"
 
-##-- Importing ----------------------------------------------------------------
+################################################################################
+## Import
+################################################################################
+declare -ag IMPORT_SOURCES=(
+    "https://raw.githubusercontent.com/nulliel/bash-starter/${BASH_STARTER_VERSION}/lib/modules"
+    "${ADDITIONAL_IMPORT_SOURCES[@]}"
+)
 
 declare -a IMPORT_HOOKS=()
 declare -a IMPORTED_FILES=()
 
+if Bootstrap::IsCacheEnabled; then
+    IMPORT_SOURCES=("${CACHE_DIR}" "${IMPORT_SOURCES[@]}")
+fi
+
+
 ##
-#
+# Attempts to import a file.
 #
 # If any hook returns a non-zero status code, the
 # module will not be imported.
+#
+# Arguments:
+#
+#   $1 :: The package to import
 ##
 Import::Main()
 {
     local package="${1}"
-    local cacheFile="${CACHE_DIR}/${package}"
+    local importFile="${CACHE_DIR}/${package}"
 
-    for file in "${IMPORTED_FILES[@]}"; do
-        if [[ "${file}" == "${package}" ]]; then
-            return 0
-        fi
-    done
-
-    if [[ "${package}" == "/"* || "${package}" == "./"* ]]; then
-        if ! Import::File "${package}"; then
-            printf "Package '%s' could not be found" "${package}" 1>&2
-            exit 1
-        fi
-
-        IMPORTED_FILES+=("${package}")
-
-        builtin source "${package}"
+    if Import::IsLoaded "${package}"; then
         return 0
     fi
 
-    local handled=1
-    for source in "${IMPORT_SOURCES[@]}"; do
-        if [[ "${source}" == "http://"* || "${source}" == "https://"* ]]; then
-            if Import::HTTP "${source}" "${package}" "${cacheFile}"; then
-                handled=0
-                break
-            fi
-        elif [[ "${source}" == "/"* || "${source}" == "./"* ]]; then
-            if Import::File "${source}/${package}"; then
-                handled=0
-                break
-            fi
-        else
-            printf "[ERROR] Unknown import source '%s'\n" "${source}" 1>&2
-            exit 1
-        fi
-    done
-
-    if [[ "${handled}" -eq 1 ]]; then
-        printf "[ERROR] Package '%s' not found in any sources\n" "${package}" 1>&2
-        exit 1
+    if ! Bootstrap::IsCacheEnabled; then
+        importFile="$(mktemp)"
     fi
 
-    if [[ ! -f "${cacheFile}" ]]; then
-        printf "[ERROR] Imported file not found in the cache\n" 1>&2
+    Import::System "${package}" || Import::Sources "${package}" "${importFile}"
+
+    if [[ ! -f "${importFile}" ]]; then
+        printf "[\e[1;91mERROR\e[0m] Unable to import package '%s'\n" "${package}" 1>&2
         exit 1
     fi
 
     IMPORTED_FILES+=("${package}")
 
-    if Import::runHooks "${cacheFile}"; then
-        builtin source "${cacheFile}"
+    if Import::runHooks "${importFile}"; then
+        builtin source "${importFile}"
     fi
 }
 
+##
+# Attempts to import a file from the filesystem.
+#
+# A file will attempt to be loaded from the filesystem if it
+# begins with either `/` or `./`
+#
+# Arguments:
+#
+#   $1 :: The package name
+#
+# Returns:
+#
+#  0 :: The file was imported
+#  1 :: The file was not imported
+##
+Import::System()
+{
+    local package="${1}"
+
+    if [[ "${package}" != "/"* && "${package}" != "./"* ]]; then
+        return 1
+    fi
+
+    if [[ ! -f "${path}" ]]; then
+        return 1
+    fi
+}
+
+##
+# Attempts to import a file from one of the sources defined
+# in `IMPORT_SOURCES`.
+#
+# Arguments:
+#
+#   $1 :: The package name
+#   $2 :: The location to save the cached file
+#
+# Returns:
+#
+#  0 :: The file was imported
+#  1 :: The file was not imported
+##
+Import::Sources()
+{
+    local package="${1}"
+    local cacheFile="${2}"
+
+    for source in "${IMPORT_SOURCES[@]}"; do
+        if [[ "${source}" == "http://"* || "${source}" == "https://"* ]]; then
+            if Import::HTTP "${source}" "${package}" "${cacheFile}"; then
+                return 0
+            fi
+        elif [[ "${source}" == "/"* || "${source}" == "./"* ]]; then
+            if Import::System "${source}/${package}"; then
+                return 0
+            fi
+        else
+            printf "[\e[1;91mERROR\e[0m] Unknown import source '%s'\n" "${source}" 1>&2
+            exit 1
+        fi
+    done
+}
+
+##
+# Attempts to import a file from a HTTP URL.
+#
+# Arguments:
+#
+#   $1 :: The base URL to download from
+#   $2 :: The package name (url extension) to download
+#   $3 :: The path to save the downloaded file to
+#
+# Returns:
+#
+#   0 :: The file was downloaded successfully
+#   1 :: The file failed to download
+##
 Import::HTTP()
 {
     local source="${1}"
@@ -101,30 +203,40 @@ Import::HTTP()
     fi
 
     if command -v curl 1>/dev/null 2>&1; then
-        curl --fail -sL --retry 3 -o "${outFile}" "${source}/${package}" || return 1
+        curl --fail -sL --retry 3 -H "Cache-Control: no-cache" -o "${outFile}" "${source}/${package}" || return 1
     else
         wget -t 3 -O - -o "${outFile}" "${source}/${package}" || return 1
     fi
 }
 
-Import::File()
+##
+# Adds an import hook.
+#
+# Import hooks allow user-defined functions to handle the
+# final import process.
+#
+# An import hook will be passed the full path to a file
+# being imported. If the function returns 0 the file will
+# be imported. If the function returns any other value, the
+# file will not be imported.
+#
+# This allows a function to act as an independant processor in
+# which it can return 0 and perform its' own import.
+#
+# This is useful for the module system outlined in core/module
+#
+# Arguments:
+#
+#   $1 :: The function to add as an import hook
+##
+Import::AddHook()
 {
-    local package="${1}"
-
-    if [[ ! -f "${package}" ]]; then
-        return 1
-    fi
-}
-
-Import::addHook()
-{
-    caller 1
-
     local functionName="$1"
 
     for element in "${IMPORT_HOOKS[@]}"; do
         if [[ "${element}" == "${functionName}" ]]; then
-            printf "[ERROR] Attempted to register hook '%s' twice\n" "${functionName}" 1>&2
+            printf "[\e[1;91mERROR\e[0m] Attempted to register hook '%s' twice\n" \
+                   "${functionName}" 1>&2
             exit 1
         fi
     done
@@ -132,12 +244,26 @@ Import::addHook()
     IMPORT_HOOKS+=("${functionName}")
 }
 
-Import::runHooks()
+##
+# Runs all `IMPORT_HOOKS` against a provided `localFile`
+#
+# See `Import::AddHook` for information on hooks.
+#
+# Arguments:
+#
+#   $1 :: The file to run hooks against
+#
+# Return:
+#
+#   0 :: If the file should be imported
+#   1 :: If the file should not be imported
+##
+Import::RunHooks()
 {
-    local cacheFile="${1}"
+    local localFile="${1}"
 
     for hook in "${IMPORT_HOOKS[@]}"; do
-        if ! "${hook}" "${cacheFile}"; then
+        if ! "${hook}" "${localFile}"; then
             return 1
         fi
     done
@@ -146,68 +272,99 @@ Import::runHooks()
 }
 
 ##
-# Ensures that the library will only be loaded once.
+# Returns whether an import has already been loaded.
 #
-# Multiple attempts to load the library will result in an
-# error and exit
+# Arguments:
+#
+#   $1 :: The package name to check
+#
+# Return:
+#
+#   0 :: The package has been loaded
+#   1 :: The package has not been loaded
 ##
-__bs__bootstrap()
+Import::IsLoaded()
 {
-    if [[ "${__bs__bootstrapped:-1}" -eq 0 ]]; then
-        printf "Attempting to bootstrap multiple times.\n" 1>&2
+    local package="${1}"
+
+    for file in "${IMPORTED_FILES[@]}"; do
+        if [[ "${file}" == "${package}" ]]; then
+            return 0
+        fi
+    done
+
+    return 1
+}
+
+################################################################################
+## Bootstrap
+################################################################################
+##
+# Ensures that the library is only loaded once.
+#
+# Multiple attempts to load the library will result in an error
+# and exit.
+##
+Bootstrap::Load()
+{
+    if [[ "${__BS__BOOTSTRAP:-1}" -eq 0 ]]; then
+        printf "[\e[1;91mERROR\e[0m] Attempted to bootstrap multiple times\n" 1>&2
         exit 1
     fi
 
-    readonly __bs__bootstrapped=0
+    readonly __BS__BOOTSTRAP=0
 }
 
-__bs__main()
+##
+# When scripts are called, their working directory is the directory in which
+# they were called, not the location they reside.
+#
+# This causes issues when including local files, as you may not be in the
+# directory you expect.
+#
+# This remedies this issue by changing the directory to the folder in which the
+# called script resides.
+#
+# Note: greadlink is an osx command
+#
+# Arguments:
+#
+#   $1 :: The path to resolve
+#
+# Returns:
+#
+#   PRINT :: The real path of the provided path
+##
+Bootstrap::ResolvePath()
 {
-    __bs__bootstrap
+    $(type -p greadlink readlink | head -1) -f "$1"
+}
 
-    ##################
+Bootstrap::Main()
+{
+    Bootstrap::Load
+
+    ############################################################################
     ## Default Modules
-    ##################
+    ############################################################################
     mkdir -p "${CACHE_DIR}"
 
     import "core/coproc"
     import "core/module"
-    import "core/colors"
+    # import "core/colors"
+    # import "console"
 
-    import "console"
-
-    ##
-    # When scripts are called, their working directory is the directory in which
-    # they were called, not the location they reside.
-    #
-    # This causes issues when including local files, as you may not be in the
-    # directory you expect.
-    #
-    # This remedies this issue by changing the directory to the folder in which the
-    # called script resides.
-    #
-    # Note: greadlink is an osx command
-    #
-    # Arguments:
-    #
-    #   $1 :: The path to resolve
-    ##
-    __bs__resolve_path()
-    {
-        $(type -p greadlink readlink | head -1) -f "$1"
-    }
-
+    ############################################################################
+    ## Paths
+    ############################################################################
     declare -g SCRIPT_ROOT
     declare -g SCRIPT_SELF
 
-    SCRIPT_ROOT="$(dirname "$(__bs__resolve_path "$0")")"
-    SCRIPT_SELF="$(dirname "$(__bs__resolve_path "${BASH_SOURCE[0]}")")"
+    SCRIPT_ROOT="$(dirname "$(Bootstrap::ResolvePath "$0")")"
+    SCRIPT_SELF="$(dirname "$(Bootstrap::ResolvePath "${BASH_SOURCE[0]}")")"
 
     readonly SCRIPT_ROOT
     readonly SCRIPT_SELF
 }
 
-################
-## Default Stubs
-################
-__bs__main "$@"
+Bootstrap::Main "$@"
